version: 2
jobs:
    build:
        working_directory: /go/src/github.com/byuoitav/deployment-testing-microservice
        docker: 
            - image: golang:1.9.2
        steps:
            - run: go get github.com/byuoitav/deployment-testing-microservice
            - run: go build
