version: 2
jobs:
    build:
        docker: 
            - image: golang:1.9.2
        steps:
            - run: go get -u github.com/byuoitav/deployment-testing-microservice
            - run: go build
